version: "3.9"

services:
  web:
    image: node:20-alpine
    container_name: carhaven_frontend_ci
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm ci && npm run build && npm run preview -- --host 0.0.0.0 --port 8081"
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
